
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-12-20T19:13:32.313+01:00
 * Generated source version: 3.1.10
 */

public class ResourceUnknownFault extends Exception {
}
