
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-29T15:12:53.866+01:00
 * Generated source version: 3.1.5
 */

public class ResourceUnknownFault extends Exception {
}
