
package org.onvif.ver10.schema;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3._2003._05.soap_envelope.Envelope;
import org.w3._2003._05.soap_envelope.Fault;


/**
 * Action Engine Event Payload data structure contains the information about the ONVIF command invocations. Since this event could be generated by other or proprietary actions, the command invocation specific fields are defined as optional and additional extension mechanism is provided for future or additional action definitions.
 * 
 * <p>Classe Java per ActionEngineEventPayload complex type.
 * 
 * <p>Il seguente frammento di schema specifica il contenuto previsto contenuto in questa classe.
 * 
 * <pre>
 * &lt;complexType name="ActionEngineEventPayload"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestInfo" type="{http://www.w3.org/2003/05/soap-envelope}Envelope" minOccurs="0"/&gt;
 *         &lt;element name="ResponseInfo" type="{http://www.w3.org/2003/05/soap-envelope}Envelope" minOccurs="0"/&gt;
 *         &lt;element name="Fault" type="{http://www.w3.org/2003/05/soap-envelope}Fault" minOccurs="0"/&gt;
 *         &lt;element name="Extension" type="{http://www.onvif.org/ver10/schema}ActionEngineEventPayloadExtension" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionEngineEventPayload", propOrder = {
    "requestInfo",
    "responseInfo",
    "fault",
    "extension"
})
public class ActionEngineEventPayload {

    @XmlElement(name = "RequestInfo")
    protected Envelope requestInfo;
    @XmlElement(name = "ResponseInfo")
    protected Envelope responseInfo;
    @XmlElement(name = "Fault")
    protected Fault fault;
    @XmlElement(name = "Extension")
    protected ActionEngineEventPayloadExtension extension;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Recupera il valore della proprietà requestInfo.
     * 
     * @return
     *     possible object is
     *     {@link Envelope }
     *     
     */
    public Envelope getRequestInfo() {
        return requestInfo;
    }

    /**
     * Imposta il valore della proprietà requestInfo.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope }
     *     
     */
    public void setRequestInfo(Envelope value) {
        this.requestInfo = value;
    }

    /**
     * Recupera il valore della proprietà responseInfo.
     * 
     * @return
     *     possible object is
     *     {@link Envelope }
     *     
     */
    public Envelope getResponseInfo() {
        return responseInfo;
    }

    /**
     * Imposta il valore della proprietà responseInfo.
     * 
     * @param value
     *     allowed object is
     *     {@link Envelope }
     *     
     */
    public void setResponseInfo(Envelope value) {
        this.responseInfo = value;
    }

    /**
     * Recupera il valore della proprietà fault.
     * 
     * @return
     *     possible object is
     *     {@link Fault }
     *     
     */
    public Fault getFault() {
        return fault;
    }

    /**
     * Imposta il valore della proprietà fault.
     * 
     * @param value
     *     allowed object is
     *     {@link Fault }
     *     
     */
    public void setFault(Fault value) {
        this.fault = value;
    }

    /**
     * Recupera il valore della proprietà extension.
     * 
     * @return
     *     possible object is
     *     {@link ActionEngineEventPayloadExtension }
     *     
     */
    public ActionEngineEventPayloadExtension getExtension() {
        return extension;
    }

    /**
     * Imposta il valore della proprietà extension.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionEngineEventPayloadExtension }
     *     
     */
    public void setExtension(ActionEngineEventPayloadExtension value) {
        this.extension = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
